version: '3'
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      jenkins:
        aliases:
          - docker
    command: --storage-driver overlay2

  my-jenkins:
    build: .
    container_name: my-jenkins
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"   # Interface web (MailHog)
      - "1025:1025"   # Port SMTP
    networks:
      - jenkins

  squash-tm:
    image: squashtest/squash          # Image Squash TM Community (dernière version)
    container_name: squash-tm
    ports:
      - "8090:8080"                   # Squash TM accessible sur http://localhost:8090/squash
    networks:
      - jenkins
    volumes:
      - ./squash_plugins:/opt/squash-tm/plugins
      - ./squash_config/application.properties:/opt/squash-tm/application.properties # TODO a tester

  orchestrator:
    image: squashtest/squash-orchestrator:latest   # Image "all-in-one" Squash Orchestrator
    container_name: squash-orchestrator
    ports:
      - "7774:7774"   # Receptionist (création de workflows)
      - "7775:7775"   # Observer (suivi des workflows)
      - "7776:7776"   # Killswitch (annulation)
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
